print("Sivapriya Rajan")
print("SJC21MCA-2042")
print("\n")
import numpy as np
array=np.random.randint(10,size=(3,3))
print(array)
inverse=np.linalg.inv(array)
print("\ninverse of the matrix is\n",inverse)
rank=np.linalg.matrix_rank(array)
print("\nrank of the given matrix is \n",rank)
determinant=np.linalg.det(array)
print("\ndeterminant of the given array is\n",determinant)
flat_array=np.ravel(array)
print("\narray in one dimension\n",flat_array)
w,v=np.linalg.eig(array)
print("\n eigen values of the matrix\n",w)
print("\n eigen vectors of the matrix\n",v)